HTTP/1.1 200 OK
Host: localhost:8000
Connection: close
X-Powered-By: PHP/8.2.12
Cache-Control: no-cache, private
Date: Sun, 21 Dec 2025 05:38:35 GMT
Content-Type: application/json
Vary: Origin

{
  "message": "Record deleted successfully"
}
