HTTP/1.1 201 Created
Host: localhost:8000
Connection: close
X-Powered-By: PHP/8.2.12
Cache-Control: no-cache, private
Date: Sun, 28 Dec 2025 12:58:29 GMT
Content-Type: application/json
Vary: Origin

{
  "data": {
    "id": 4,
    "title": "Issue with my review",
    "description": "I placed an review yesterday but haven't received any confirmation email. Order was for haircut service at 10:00 AM.",
    "status": "pending",
    "created_at": "2025-12-28T12:58:29.000000Z",
    "updated_at": "2025-12-28T12:58:29.000000Z"
  },
  "message": "Ticket created successfully."
}
