HTTP/1.1 200 OK
Date: Wed, 17 Dec 2025 10:19:21 GMT
Server: Apache/2.4.58 (Ubuntu)
Cache-Control: no-cache, private
Vary: Origin
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json

[
  {
    "id": 2,
    "name": "VonRueden-White",
    "status": "registered",
    "phone": "863.559.4385",
    "person_in_charge": "Prof. Adonis Lueilwitz",
    "address": "43019 Ferry Fork Apt. 093\nNew Misty, OK 71662",
    "address_lat": "37.0614250",
    "address_long": "95.2989640",
    "open_hour_today": "closed",
    "designers": []
  }
]