#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running lint..."
npm run lint || exit 1

echo "➕ Format code..."
npm run format || exit 1

echo "➕ Adding fixed files..."
git add . || exit 1

echo "🏗️ Running build..."
npm run build || exit 1